In [2]:
#2021.05.31. MON
#Hankyeong

#01. 넘파이를 사용하여 다음과 같은 행렬을 만드시오. 
#         10 20 30 40 
#         50 60 70 80
import numpy as np 
matrix = np.array([[10,20,30,40],[50,60,70,80]])
matrix

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [3]:
#02. 다음 행렬과 같은 행렬이 있다. 
#    m = np.array([[ 0,  1,  2,  3,  4], 
#                  [ 5,  6,  7,  8,  9], 
#                  [10, 11, 12, 13, 14]])
#(1)이 행렬에서 값 7 을 인덱싱한다.
m = np.array([[ 0, 1, 2, 3, 4], [ 5, 6, 7, 8, 9], [10, 11, 12, 13, 14]])
m[1,2]

7

In [12]:
#(2) 이 행렬에서 값 14 을 인덱싱한다.
m[-1,-1]

14

In [15]:
#(3) 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
m[1,1:3]

array([6, 7])

In [17]:
#(4) 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
m[1:3,2]

array([ 7, 12])

In [18]:
#(5) 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
m[:2,3:5]

array([[3, 4],
       [8, 9]])

In [4]:
#03. 2번의 행렬 m을 1차원 벡터 f 로 변환한 후 다음의 문제를 푸시오.
#(1) 이 배열에서 3의 배수를 찾아라.
f = m.flatten()
f[f%3==0]

array([ 0,  3,  6,  9, 12])

In [23]:
#(2) 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
f[f%4==1]

array([ 1,  5,  9, 13])

In [24]:
#(3) 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
f[np.logical_and(f%3==0,f%4==1)]

array([9])

In [150]:
#04. 값을 직접 입력하지 말고 우측의 행렬을 만드시오.
#           2, 1, 0, 0, 0 
#           3, 2, 1, 0, 0 
#           0, 3, 2, 1, 0 
#           0, 0, 3, 2, 1
#           0, 0, 0, 3, 2
np.eye(5,5)*2+np.eye(5,5,1)+np.eye(5,5,-1)*3

array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

In [102]:
#05. 0에서 10까지 랜덤 실수값으로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구하시오.
np.random.seed(2021)
matrix_2 = np.random.uniform(0,10,30).reshape(5,6).round(2)
print(matrix_2)

[[6.06 7.33 1.39 3.13 9.97 1.28]
 [1.79 7.53 6.62 7.84 0.97 0.59]
 [9.62 6.17 0.87 5.61 6.17 9.64]
 [5.74 3.71 4.52 2.02 5.69 1.95]
 [5.84 4.76 5.18 8.23 7.32 0.69]]


In [41]:
#(1) 전체의 최댓값
np.max(matrix_2)

9.97

In [42]:
#(2) 각 행의 합
matrix_2.sum(axis=1)

array([29.16, 25.34, 38.08, 23.63, 32.02])

In [43]:
#(3) 각 행의 최댓값
matrix_2.max(axis=1)

array([9.97, 7.84, 9.64, 5.74, 8.23])

In [44]:
#(4) 각 열의 평균
matrix_2.mean(axis=0)

array([5.81 , 5.9  , 3.716, 5.366, 6.024, 2.83 ])

In [45]:
#(5) 각 열의 최솟값
matrix_2.min(axis=0)

array([1.79, 3.71, 0.87, 2.02, 0.97, 0.59])

In [5]:
#06. 다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은 배열이다. 영어 성적을 기준으로 재정렬하시오. 
#    np.array([[  1,  2,   3,  4], 
#              [ 46, 99, 100, 71], 
#              [ 81, 59,  90, 100]])
grade=np.array([[ 1, 2, 3, 4], [ 46, 99, 100, 71], [ 81, 59, 90, 100]])
grade

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [12]:
grade[:,grade.argsort()[1]]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

In [ ]:
#if R,
#library(dplyr)
#grade <- grade %>% as.data.frame()
#grade <- grade %>% rename(english=grade$"[,2]")
#grade_t <- grade %>% t()
#grade_t <- grade_t %>% arrange(desc(english))

In [14]:
#07.주사위를 100번 던지는 가상 실험을 파이썬으로 작성하고, 던져서 나오는 숫자의 평균을 구하시오.
python = np.random.uniform(1,6,100).round(0)
python

array([3., 4., 2., 4., 2., 2., 6., 3., 1., 3., 4., 6., 1., 2., 3., 3., 4.,
       3., 3., 1., 2., 3., 4., 1., 2., 1., 5., 2., 2., 3., 3., 2., 5., 2.,
       4., 3., 1., 2., 5., 1., 2., 3., 6., 1., 1., 4., 5., 2., 2., 4., 6.,
       6., 4., 3., 4., 6., 4., 1., 4., 2., 5., 5., 5., 2., 2., 4., 4., 2.,
       3., 5., 4., 3., 4., 6., 1., 2., 5., 1., 4., 2., 3., 5., 3., 4., 5.,
       1., 5., 5., 3., 5., 5., 3., 2., 1., 3., 2., 2., 6., 2., 2.])

In [119]:
python.mean()

3.53

In [12]:
#08. 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하시오.
np.random.seed(2021)
10000-(np.random.normal(0,1,250)*0.01*10000).round(0)

array([ 9851.,  9932., 10042., 10081.,  9944., 10071.,  9887.,  9935.,
        9989.,  9958.,  9988., 10084.,  9959.,  9990., 10191.,  9890.,
       10140., 10023., 10134.,  9970., 10072.,  9746.,  9868.,  9993.,
       10026.,  9986.,  9885.,  9862., 10047.,  9948.,  9851.,  9852.,
        9927., 10039.,  9972.,  9995., 10104., 10016., 10279.,  9964.,
        9976.,  9952.,  9979.,  9908., 10141.,  9878., 10055.,  9909.,
       10098., 10063.,  9917., 10128., 10035., 10108.,  9903.,  9959.,
       10013., 10067.,  9878., 10093.,  9858., 10012.,  9929.,  9928.,
        9986., 10065., 10067.,  9913.,  9900., 10037.,  9887.,  9921.,
       10175., 10081., 10141., 10080.,  9920.,  9824., 10008.,  9958.,
        9984., 10006., 10054.,  9910.,  9978.,  9872.,  9937.,  9964.,
        9636., 10120., 10133.,  9874., 10065.,  9775., 10101., 10013.,
       10043.,  9957.,  9924., 10099., 10074.,  9954.,  9874., 10044.,
        9946.,  9943., 10044.,  9923.,  9952., 10088., 10068.,  9955.,
      

In [ ]:
#그러나, 위의 코드는 전일의 종가를 반영하지 못함.

In [32]:
np.random.seed(2021)
price = 10000
variable_price = np.random.normal(0,1,250)*0.01*price
for i in range(250) :
    price = price + variable_price[i]
    print(f'{price:>5,.0f}원')

10,149원
10,216원
10,175원
10,094원
10,150원
10,079원
10,192원
10,257원
10,267원
10,309원
10,322원
10,238원
10,279원
10,289원
10,098원
10,208원
10,068원
10,046원
9,912원
9,943원
9,870원
10,125원
10,257원
10,264원
10,238원
10,252원
10,367원
10,505원
10,457원
10,510원
10,658원
10,806원
10,879원
10,840원
10,868원
10,873원
10,769원
10,753원
10,473원
10,510원
10,534원
10,581원
10,602원
10,694원
10,553원
10,675원
10,621원
10,711원
10,613원
10,550원
10,632원
10,504원
10,469원
10,361원
10,459원
10,500원
10,487원
10,419원
10,542원
10,449원
10,591원
10,579원
10,649원
10,721원
10,736원
10,670원
10,603원
10,690원
10,790원
10,754원
10,866원
10,946원
10,771원
10,690원
10,548원
10,468원
10,548원
10,724원
10,716원
10,758원
10,774원
10,768원
10,714원
10,804원
10,827원
10,955원
11,018원
11,054원
11,418원
11,298원
11,165원
11,291원
11,226원
11,450원
11,349원
11,336원
11,293원
11,336원
11,412원
11,312원
11,238원
11,284원
11,410원
11,365원
11,419원
11,476원
11,433원
11,509원
11,557원
11,469원
11,401원
11,446원
11,374원
11,230원
11,445원
11,450원
11,515원
11,407원
11,432원
11,469원
11,510원
11,630원
11,738원
11,766원
11,859원
11,