In [1]:
#2021.05.31. MON
#Hankyeong

##데이터 사이언스 스쿨, datascienceschool.net
##CH03. 넘파이 배열 프로그래밍
#01. Numpy(Numerical Python)의 특징
#(1) 일반 리스트에 비해 빠르고, 메모리를 효율적으로 사용할 수 있음.

#(2) 반복문 없이 데이터 배열에 대한 처리를 지원함.

#(3) 선형대수와 관련된 다양한 기능을 제공함.

#(4) C, C++ 등의 언어와 통합이 가능함.

#02. Array Shape
#(1) 1차원, Vector
import numpy as np 
vector_1 = np.array([1,4,5,8],float)
print(vector_1,vector_1.shape)

[1. 4. 5. 8.] (4,)


In [ ]:
#PLUS. vector의 차원구조는 R과는 다르게 (n,)으로 출력됨.

In [2]:
#(2) 2차원, Matrix
matrix_1 = np.array([[1,4],[5,8]],float)
print(matrix_1,matrix_1.shape)

[[1. 4.]
 [5. 8.]] (2, 2)


In [3]:
#(3) 3차원, Tensor
tensor_1 = np.array([[[1,4],[5,8]],[[11,14],[15,18]]],float)
print(tensor_1,tensor_1.shape)

[[[ 1.  4.]
  [ 5.  8.]]

 [[11. 14.]
  [15. 18.]]] (2, 2, 2)


In [4]:
#03. 변수의 차원을 확인하는 속성, .ndim
vector_1.ndim , matrix_1.ndim , tensor_1.ndim

(1, 2, 3)

In [5]:
#04. 변수의 원소 개수를 확인하는 속성, .size
vector_1.size, matrix_1.size, tensor_1.size

(4, 4, 8)

In [7]:
#05. 객체의 데이터 형태(type)을 확인하는 속성, dtype
vector_1.dtype, matrix_1.dtype, tensor_1.dtype

(dtype('float64'), dtype('float64'), dtype('float64'))

In [9]:
#06. reshape() 메쏘드를 이용해 넘파이 배열 구조 변경하기. 
#(1) tensor_1를 matrix 구조로 변경하기. 
tensor_1.reshape(2,4)

array([[ 1.,  4.,  5.,  8.],
       [11., 14., 15., 18.]])

In [ ]:
#PLUS. (단, 원소의 개수(size)는 동일해야함. 

In [8]:
#(2) tensor_1을 vector 구조로 변경하기.
tensor_1.reshape(8,)

array([ 1.,  4.,  5.,  8., 11., 14., 15., 18.])

In [13]:
#TIP. 인자에 -1을 기입하면 행 열을 알아서 맞춰줌. 단, 나머지 인자값은 지정해야함.  
tensor_1.reshape(-1,1) 

array([[ 1.],
       [ 4.],
       [ 5.],
       [ 8.],
       [11.],
       [14.],
       [15.],
       [18.]])

In [15]:
#08. flatten() 메쏘드를 이용해 다차원 배열을 vector로 변환하기. 
tensor_1.flatten()

array([ 1.,  4.,  5.,  8., 11., 14., 15., 18.])

In [15]:
#09. 넘파이 배열의 인덱싱과 슬라이싱하기. 
a = np.arange(6)  #a= np.array(range(6))
a 

array([0, 1, 2, 3, 4, 5])

In [16]:
a=np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [17]:
#(1) 기존의 list의 방법으로 인덱싱하기.
a[0][1]

1

In [18]:
#(2) numpy array 방식으로 인덱싱하기. 
a[0,1]

1

In [20]:
#(3) list와는 달리 배열은 행 열 모두에 슬라이싱이 가능함.
a[0:2,0:2]

array([[0, 1],
       [3, 4]])

In [21]:
#10. 다양한 메쏘드로 배열 생성하기. 
#(1) arange() 
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(0,1.1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [24]:
#TIP. 부동소수점에 대한 논의 
#컴퓨터는 정확하게 실수(특히 소수점)를 정확하게 표현하지 못함.
#두 실수의 비교는 차이가 아주 작냐를 물어봐야함.
np.arange(0,1.1,0.1).tolist()

[0.0,
 0.1,
 0.2,
 0.30000000000000004,
 0.4,
 0.5,
 0.6000000000000001,
 0.7000000000000001,
 0.8,
 0.9,
 1.0]

In [25]:
np.arange(0,1.1,0.1)[3] == 0.3

False

In [26]:
np.abs(np.arange(0,1.1,0.1)[3] - 0.3) < 10**-8

True

In [67]:
#(2) zeros() 
b = np.zeros((5,),dtype=np.int64)
b

array([0, 0, 0, 0, 0], dtype=int64)

In [68]:
#(3) ones()
c = np.ones((2,4),dtype=np.int8)
c

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [73]:
#(4) empty()
d = np.empty((2,5))
d

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ]])

In [ ]:
#Q. 왜 empty() 메쏘드를 설정했는데 값이 따로 지정되었는가?
#A. ones(), zeros()는 변수를 생성하면서 메모리에 초기화와 할당을 했지만, empty()는 메모리에 할당만 했고

In [27]:
#(5) ones_like()
e = np.arange(24).reshape(4,-1)
np.ones_like(e)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [28]:
#(6) zeros_like()
np.zeros_like(e)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [29]:
#(7) identity(), 대각 원소가 1인 정방행렬(단위행렬, identity) 만들기.
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#PLUS. 회귀분석과 머신러닝에 대한 논의
#      Y(종속변수) = beta_1(회귀계수) * X(독립변수) + e(오차항)  ※hat은 생략함.
#      Y(타겟)     = X(피쳐) %*% w(가중치, weight) + b(편향, bias)

In [83]:
#(8) eye(), 대각 원소가 1인 행렬만들기.  
#①
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [31]:
#② k 파라미터에 -1만큼 주면 좌측으로 움직임.
np.eye(3,5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [32]:
#③ k=1이면 우측으로 움직임.
np.eye(N=3,M=5,k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [33]:
#11. numpy 패키지로 무작위 추출(random sampling)하고 배열로 만들기. 
np.random.seed(2021)
np.random.uniform(0, 1, 9).reshape(3,3)

array([[0.60597828, 0.73336936, 0.13894716],
       [0.31267308, 0.99724328, 0.12816238],
       [0.17899311, 0.75292543, 0.66216051]])

In [34]:
#12. 정규분포를 따르는 표본으로 랜덤 샘플링하고 배열로 만들기.
np.random.seed(2021)
np.random.normal(0,1,9).reshape(3,3)

array([[-0.19009954,  0.13407709, -0.75051215],
       [ 0.21162099,  2.0448903 ,  1.07526774],
       [ 0.07902026,  0.49328237, -0.79136747]])

In [52]:
#13. 이항분포를 따르는 표본으로 랜덤 샘플링하고 배열로 만들기.
np.random.binomial(1,0.5,12).reshape(3,-1)

array([[1, 0, 0, 1],
       [1, 0, 1, 0],
       [1, 0, 0, 1]])