In [2]:
#2021.05.31. MON
#Hankyeong

#14. 여러 계산 메쏘드와 axis 파라미터를 이용하기. 
import numpy as np 
a= np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
#(1) sum()
a.sum()

78

In [5]:
#TIP. 계산함수에는 axis 파라미터가 있는데, axis=0은 열기준, axis=1은 행기준임. 
a.sum(axis=0)

array([15, 18, 21, 24])

In [11]:
a.sum(axis=1)

array([10, 26, 42])

In [6]:
#(2) min()
a.min(axis=0)

array([1, 2, 3, 4])

In [14]:
#(4) mean()
a.mean(axis=0)

array([5., 6., 7., 8.])

In [9]:
#(4) var() = variation
a.var(axis=0)

array([10.66666667, 10.66666667, 10.66666667, 10.66666667])

In [8]:
#(5) std() = standard deviation
a.std(axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [21]:
#15. T를 이용해 전치행렬(transpose matrix)로 만들기.
b= np.arange(1,4+1).reshape(2,2)
b.T

array([[1, 3],
       [2, 4]])

In [22]:
#16. vstack() 메쏘드를 이용해 배열 밑으로 합치기. =R의 rbind()
c= np.array([[5,6]])
np.vstack((b,c))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
#17. hstack() 메쏘드를 이용해 배열 왼쪽으로 합치기. =R의 cbind()
np.hstack((b,c.T))

array([[1, 2, 5],
       [3, 4, 6]])

In [27]:
#18. concatenate() 메쏘드를 이용해 배열 합치기.
np.concatenate((b,c),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
np.concatenate((b,c.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [35]:
#19. 배열의 원소 간 계산(element-wise operation)
#(1) +
b + b

array([[2, 4],
       [6, 8]])

In [36]:
#(2) -
b - b

array([[0, 0],
       [0, 0]])

In [37]:
#(3) *
b * b

array([[ 1,  4],
       [ 9, 16]])

In [38]:
#(4) /
b / b

array([[1., 1.],
       [1., 1.]])

In [41]:
#20. dot()함수로 내적(Dot product) 시행하기. 
#(1) 방법1
d = np.arange(1,6+1).reshape(2,3)
d.dot(d.T)

array([[14, 32],
       [32, 77]])

In [42]:
#(2) 방법2
np.dot(d,d.T) 

array([[14, 32],
       [32, 77]])

In [43]:
#21. 차원이 맞지 않는 변수들끼리 연산하기. (Broadcasting)
#(1) 매트릭스와 스칼라의 가감승제
#① +
b + 10

array([[11, 12],
       [13, 14]])

In [44]:
#② -
b - 10

array([[-9, -8],
       [-7, -6]])

In [46]:
#③ *
b * 10

array([[10, 20],
       [30, 40]])

In [48]:
#④ /
b / 2 

array([[0.5, 1. ],
       [1.5, 2. ]])

In [49]:
#PLUS. **2
b ** 2 

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [54]:
#(2) 매트릭스와 벡터의 연산
#①
b + np.array([10,20]) 

array([[11, 22],
       [13, 24]])

In [58]:
#PLUS. 열 기준으로 더하고 싶으면 전치행렬을 취해야함.
b + np.array([10,20]).T

array([[11, 22],
       [13, 24]])

In [64]:
#PLUS. 단, 벡터의 길이가 행렬의 행길이 혹은 열길이가 맞아야함. 
a + np.array([10,20]) #이건 안되니라

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [55]:
#② -
b - np.array([10,20]) 

array([[ -9, -18],
       [ -7, -16]])

In [56]:
#③ *
b * np.array([10,20]) 

array([[10, 40],
       [30, 80]])

In [57]:
#④ /
b / np.array([10,20]) 

array([[0.1, 0.1],
       [0.3, 0.2]])

In [59]:
#22. 배열의 원소에 따라 비교하기. 
#(1) 
e = np.arange(5)
e > 2

array([False, False, False,  True,  True])

In [68]:
#(2) np.all() 함수로 비교하기.
np.all(e>2)

False

In [67]:
#(3) np.any() 함수로 비교하기. 
np.any(e>2)

True

In [69]:
#PLUS. 응용하여 필터링하기. = Boolean Indexing
e[e>2]

array([3, 4])

In [70]:
#23. logical operation
#(1) and 연산자
np.logical_and(e>0, e<3)


array([False,  True,  True, False, False])

In [72]:
#(2) or 연산자
np.logical_or(e>0, e<3)

array([ True,  True,  True,  True,  True])

In [71]:
#(3) not 연산자
np.logical_not(e>0, e<3)


array([ True, False, False, False, False])

In [74]:
#24. where() 함수로 조건에 따라 처리하기. = R의 ifelse()함수
np.where(e>=2,"BIG","SMALL")

array(['SMALL', 'SMALL', 'BIG', 'BIG', 'BIG'], dtype='<U5')

In [77]:
#25. nan(Not A Number), inf(Infinite) 원소 생성과 판별함수 사용하기.
#(1)
f=np.array([1, np.nan, np.inf], float)
f

array([ 1., nan, inf])

In [78]:
#(2) isnan() 함수로 nan값 판별하기.
np.isnan(f)

array([False,  True, False])

In [81]:
#(3) isinfinite() 함수로 inf값 판별하기.
np.isinf(f)

array([ True, False, False])

In [83]:
#PLUS. isfinite() 함수로 실수값 판별하기.
np.isfinite(f)

array([ True, False, False])

In [85]:
#26. argmax(), argmin() 함수로 원소 최댓값, 최솟값의 인덱스 파악하기.
g = np.arange(6,12+1)
g

array([ 6,  7,  8,  9, 10, 11, 12])

In [86]:
np.argmax(g), np.argmin(g)

(6, 0)

In [ ]:
#CAUTION. 원소값이 아닌 인덱스값임! 

In [87]:
#PLUS. 매트릭스의 경우, 행 기준
h= np.arange(12).reshape(3,-1)
h

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [102]:
np.argmax(h, axis=0)

array([2, 2, 2, 2], dtype=int64)

In [103]:
#PLUS. 매트릭스의 경우, 열 기준
np.argmax(h, axis=1)

array([3, 3, 3], dtype=int64)