In [1]:
#2021.06.18. FRI
#Hankyeong 

##CH02. 데이터셋 전처리
#00. 패키지 호출
import pandas as pd 
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

#01. 레이블인코딩(Label Encoding)
#(1) Factor 변수 설정하기. 
items = ['TV','냉장고','전자렌지','믹서','컴퓨터','선풍기','선풍기','믹서']

#(2) 객체 설정하기. 
encoder = LabelEncoder()

#(3) fitting(일종의 학습)하기. 
encoder.fit(items)

LabelEncoder()

In [2]:
#(4) 인코딩값 반환하기. 
labels = encoder.transform(items)
labels

array([0, 1, 4, 2, 5, 3, 3, 2])

In [3]:
#PLUS. 실전응용하기. 
encoder = LabelEncoder()
labels = encoder.fit_transform(items)
labels

array([0, 1, 4, 2, 5, 3, 3, 2], dtype=int64)

In [4]:
#02. 원핫인코딩(One-hot encoding)
#(1) 레이블값 구조 변환하기. 
labels = labels.reshape(-1,1)
labels

array([[0],
       [1],
       [4],
       [2],
       [5],
       [3],
       [3],
       [2]], dtype=int64)

In [5]:
#(2) 객체 생성하기. 
oh_encoder = OneHotEncoder()

#(3) fitting하기. 
oh_encoder.fit(labels)

OneHotEncoder()

In [6]:
#(4) 인코딩값 반환하기. 
one_hot = oh_encoder.transform(labels)
one_hot.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [7]:
#PLUS. 실전응용하기. 
labels = LabelEncoder().fit_transform(items)
oh_encoder = OneHotEncoder()
one_hot = oh_encoder.fit_transform(labels.reshape(-1,1))
one_hot.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [8]:
#03. 표준 정규화(Standard Scaler)
#(1) 데이터셋 불러오기. 
iris = load_iris()

#(2) 데이터프레임으로 변환하기. 
df_iris = pd.DataFrame(iris.data, columns=iris.feature_names)
df_iris['species'] = iris.target
df_iris

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     species  
0          0  
1          0  
2          0  
3          0  
4          0  
..       ...  
145        2  
146        2  
147        2  
148        2  
149        2  

[150 rows x 5 columns]

In [9]:
#(3) 객체 생성하기. 
std_scaler = StandardScaler()

#(4) 스케일링 처리하기. 
iris_std = std_scaler.fit_transform(iris.data)

#(5) 처리한 값으로 데이터프레임 생성하기. 
df_iris_std = pd.DataFrame(iris_std, columns=iris.feature_names)
df_iris_std['species'] = iris.target
df_iris_std

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0            -0.900681          1.019004          -1.340227         -1.315444   
1            -1.143017         -0.131979          -1.340227         -1.315444   
2            -1.385353          0.328414          -1.397064         -1.315444   
3            -1.506521          0.098217          -1.283389         -1.315444   
4            -1.021849          1.249201          -1.340227         -1.315444   
..                 ...               ...                ...               ...   
145           1.038005         -0.131979           0.819596          1.448832   
146           0.553333         -1.282963           0.705921          0.922303   
147           0.795669         -0.131979           0.819596          1.053935   
148           0.432165          0.788808           0.933271          1.448832   
149           0.068662         -0.131979           0.762758          0.790671   

     species  
0          0  
1          0  
2          0  
3          0  
4          0  
..       ...  
145        2  
146        2  
147        2  
148        2  
149        2  

[150 rows x 5 columns]

In [10]:
#04. 최대최소 정규화(MinMax Scaler)
#(1) 객체 생성하기. 
mm_scaler = MinMaxScaler()

#(2) 스케일링 처리하기. 
iris_mm = mm_scaler.fit_transform(iris.data)

#(3) 처리한 값으로 데이터프레임 생성하기. 
df_iris_mm = pd.DataFrame(iris_mm, columns=iris.feature_names)
df_iris_mm['species'] = iris.target
df_iris_mm

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0             0.222222          0.625000           0.067797          0.041667   
1             0.166667          0.416667           0.067797          0.041667   
2             0.111111          0.500000           0.050847          0.041667   
3             0.083333          0.458333           0.084746          0.041667   
4             0.194444          0.666667           0.067797          0.041667   
..                 ...               ...                ...               ...   
145           0.666667          0.416667           0.711864          0.916667   
146           0.555556          0.208333           0.677966          0.750000   
147           0.611111          0.416667           0.711864          0.791667   
148           0.527778          0.583333           0.745763          0.916667   
149           0.444444          0.416667           0.694915          0.708333   

     species  
0          0  
1          0  
2          0  
3          0  
4          0  
..       ...  
145        2  
146        2  
147        2  
148        2  
149        2  

[150 rows x 5 columns]